/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeliusRpcUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivyAppSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackerNewsWeb": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}